version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../app:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123@123@sql
      MYSQL_DATABASE: financial_reporting_system
      MYSQL_USER: waqar
      MYSQL_PASSWORD: 123@123@sql
    ports:
      - "3306:3306"
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123@123@sql
    ports:
      - "8080:80"
    networks:
      - app_network

volumes:
  node_modules:

networks:
  app_network:
    driver: bridge
